include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    dead_code: error
    unused_element: error
    unused_import: error

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - require_trailing_commas

plugins:
  riverpod_lint: <latest version from https://pub.dev/packages/riverpod_lint>


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
